/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/app'
import { Route as AppIndexImport } from './routes/_app/index'
import { Route as AppTestIndexImport } from './routes/_app/test/index'
import { Route as AppTestChatImport } from './routes/_app/test/chat'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/_app/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppTestIndexRoute = AppTestIndexImport.update({
  id: '/_app/test/',
  path: '/test/',
  getParentRoute: () => rootRoute,
} as any)

const AppTestChatRoute = AppTestChatImport.update({
  id: '/_app/test/chat',
  path: '/test/chat',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof rootRoute
    }
    '/_app/test/chat': {
      id: '/_app/test/chat'
      path: '/test/chat'
      fullPath: '/test/chat'
      preLoaderRoute: typeof AppTestChatImport
      parentRoute: typeof rootRoute
    }
    '/_app/test/': {
      id: '/_app/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AppTestIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/app': typeof AppRoute
  '/': typeof AppIndexRoute
  '/test/chat': typeof AppTestChatRoute
  '/test': typeof AppTestIndexRoute
}

export interface FileRoutesByTo {
  '/app': typeof AppRoute
  '/': typeof AppIndexRoute
  '/test/chat': typeof AppTestChatRoute
  '/test': typeof AppTestIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/app': typeof AppRoute
  '/_app/': typeof AppIndexRoute
  '/_app/test/chat': typeof AppTestChatRoute
  '/_app/test/': typeof AppTestIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/app' | '/' | '/test/chat' | '/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/app' | '/' | '/test/chat' | '/test'
  id: '__root__' | '/app' | '/_app/' | '/_app/test/chat' | '/_app/test/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTestChatRoute: typeof AppTestChatRoute
  AppTestIndexRoute: typeof AppTestIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRoute,
  AppIndexRoute: AppIndexRoute,
  AppTestChatRoute: AppTestChatRoute,
  AppTestIndexRoute: AppTestIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/app",
        "/_app/",
        "/_app/test/chat",
        "/_app/test/"
      ]
    },
    "/app": {
      "filePath": "app.tsx"
    },
    "/_app/": {
      "filePath": "_app/index.tsx"
    },
    "/_app/test/chat": {
      "filePath": "_app/test/chat.tsx"
    },
    "/_app/test/": {
      "filePath": "_app/test/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
