/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/app'
import { Route as IndexImport } from './routes/index'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AppTestIndexImport } from './routes/app/test/index'
import { Route as AppTestChatImport } from './routes/app/test/chat'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppTestIndexRoute = AppTestIndexImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => AppRoute,
} as any)

const AppTestChatRoute = AppTestChatImport.update({
  id: '/test/chat',
  path: '/test/chat',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/app/test/chat': {
      id: '/app/test/chat'
      path: '/test/chat'
      fullPath: '/app/test/chat'
      preLoaderRoute: typeof AppTestChatImport
      parentRoute: typeof AppImport
    }
    '/app/test/': {
      id: '/app/test/'
      path: '/test'
      fullPath: '/app/test'
      preLoaderRoute: typeof AppTestIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppTestChatRoute: typeof AppTestChatRoute
  AppTestIndexRoute: typeof AppTestIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppTestChatRoute: AppTestChatRoute,
  AppTestIndexRoute: AppTestIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/test/chat': typeof AppTestChatRoute
  '/app/test': typeof AppTestIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/app/test/chat': typeof AppTestChatRoute
  '/app/test': typeof AppTestIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/test/chat': typeof AppTestChatRoute
  '/app/test/': typeof AppTestIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/app/' | '/app/test/chat' | '/app/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/app/test/chat' | '/app/test'
  id: '__root__' | '/' | '/app' | '/app/' | '/app/test/chat' | '/app/test/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app": {
      "filePath": "app.tsx",
      "children": [
        "/app/",
        "/app/test/chat",
        "/app/test/"
      ]
    },
    "/app/": {
      "filePath": "app/index.tsx",
      "parent": "/app"
    },
    "/app/test/chat": {
      "filePath": "app/test/chat.tsx",
      "parent": "/app"
    },
    "/app/test/": {
      "filePath": "app/test/index.tsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
